version: '3.3'

services:
  backend:
    build: ./code/backend
    expose:
     - 5000
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - CONFIG_DIR=/usr/src/backend/Wallet_EDUSETUDB_2
      - WALLET_LOCATION=/usr/src/backend/Wallet_EDUSETUDB_2
    volumes:
      - ./Wallet_EDUSETUDB_2:/usr/src/backend/Wallet_EDUSETUDB_2
  ui:
    build: ./code/ui
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - "backend:backend"

volumes:
  Wallet_EDUSETUDB_2: