version: '3.3'

services:
  backend:
    build: ./code/backend
    expose:
     - 5000
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
  ui:
    build: ./code/ui
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - "backend:backend"
